FROM python:2-alpine3.7


COPY requirements_flask.txt /tmp/requirements_flask.txt
RUN apk update && \
  apk add --virtual .build-deps gcc python-dev musl-dev libxml2-dev libxml2 && \
  apk add --no-cache libxslt-dev sqlite postgresql-dev postgresql-libs && \
  pip install --prefer-binary -r /tmp/requirements_flask.txt && \
  rm -r /root/.cache && \
  apk del .build-deps


RUN echo "http://dl-4.alpinelinux.org/alpine/v3.7/main" >> /etc/apk/repositories && \
    echo "http://dl-4.alpinelinux.org/alpine/v3.7/community" >> /etc/apk/repositories
RUN apk update
RUN apk add chromium chromium-chromedriver

COPY . /app
RUN chmod +x /app/entrypoint.sh
WORKDIR /app
RUN pip install -e /app/core
# ENTRYPOINT [ "/bin/sh", "-c","while true; do sleep 30; done;"]
ENTRYPOINT ["python"]
ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["python","-m" ,"celery", "-A", "celery_factory", "worker", "--loglevel=info","--concurrency","1"]
# CMD ["celery","celery", "-A", "celery_factory", "worker", "--loglevel=info"]
# CMD ["/bin/sh","-c","while true; do sleep 30; done;"]
