FROM python:2-alpine3.7


COPY ./migrations/requirements_flask.txt /tmp/requirements_flask.txt
RUN apk update && \
  apk add --virtual .build-deps gcc python-dev musl-dev libxml2-dev libxml2 && \
  apk add --no-cache libxslt-dev sqlite postgresql-dev postgresql-libs && \
  pip install --prefer-binary -r /tmp/requirements_flask.txt && \
  rm -r /root/.cache && \
  apk del .build-deps



COPY ./migrations/. /migrations
COPY ./core /migrations/core
RUN chmod +x /migrations/entrypoint.sh
WORKDIR /migrations

RUN pip install -e /migrations/core
#
# ENTRYPOINT [ '/bin/sh', "-c",'while true; do sleep 30; done;']

# CMD ["python"]
ENTRYPOINT ["/migrations/entrypoint.sh"]

# CMD ["python","-u","main.py"]
# CMD ["/bin/sh","-c","while true; do sleep 30; done;"]
